// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';
import type { QueryOperationTypes as PgTargetQueryOps } from '@prisma/orm-postgres/target/operation-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'f7c3243779e635472d046b6c9b1ed848cbd3d91dc44211fa2aeaa890d632a60e'>;
export type ExecutionHash =
  ExecutionHashBase<'af7f13c8dddb9905bf206ab39caea12fc9cb311aa6323cd6bcc02b6150437190'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgTargetQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Category: {
      readonly description: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: Varchar<100>;
    };
    readonly Location: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: Varchar<100>;
      readonly type: 'STORAGE' | 'STAGING' | 'RETURNS';
      readonly warehouseId: CodecTypes['pg/int4@1']['output'];
    };
    readonly Product: {
      readonly categoryId: CodecTypes['pg/int4@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly name: Varchar<255>;
      readonly reorderLevel: CodecTypes['pg/int4@1']['output'];
      readonly sku: Varchar<100>;
      readonly unit: Varchar<50>;
      readonly updatedAt: CodecTypes['pg/timestamp-temporal@1']['output'];
    };
    readonly StockLevel: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly locationId: CodecTypes['pg/int4@1']['output'];
      readonly productId: CodecTypes['pg/uuid@1']['output'];
      readonly quantity: CodecTypes['pg/int4@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamp-temporal@1']['output'];
    };
    readonly Transaction: {
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly createdById: CodecTypes['pg/uuid@1']['output'];
      readonly fromLocationId: CodecTypes['pg/int4@1']['output'] | null;
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly notes: CodecTypes['pg/text@1']['output'] | null;
      readonly productId: CodecTypes['pg/uuid@1']['output'];
      readonly quantity: CodecTypes['pg/int4@1']['output'];
      readonly reference: Varchar<100> | null;
      readonly status: 'DRAFT' | 'VALIDATED' | 'CANCELLED';
      readonly toLocationId: CodecTypes['pg/int4@1']['output'] | null;
      readonly type: 'RECEIPT' | 'DELIVERY' | 'TRANSFER' | 'ADJUSTMENT';
    };
    readonly User: {
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly email: Varchar<255>;
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly name: Varchar<255>;
      readonly passwordHash: Varchar<255>;
      readonly role: 'ADMIN' | 'MANAGER' | 'STAFF';
    };
    readonly Warehouse: {
      readonly address: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly isActive: CodecTypes['pg/bool@1']['output'];
      readonly name: Varchar<100>;
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Category: {
      readonly description: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['sql/varchar@1']['input'];
    };
    readonly Location: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['sql/varchar@1']['input'];
      readonly type: 'STORAGE' | 'STAGING' | 'RETURNS';
      readonly warehouseId: CodecTypes['pg/int4@1']['input'];
    };
    readonly Product: {
      readonly categoryId: CodecTypes['pg/int4@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly name: CodecTypes['sql/varchar@1']['input'];
      readonly reorderLevel: CodecTypes['pg/int4@1']['input'];
      readonly sku: CodecTypes['sql/varchar@1']['input'];
      readonly unit: CodecTypes['sql/varchar@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamp-temporal@1']['input'];
    };
    readonly StockLevel: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly locationId: CodecTypes['pg/int4@1']['input'];
      readonly productId: CodecTypes['pg/uuid@1']['input'];
      readonly quantity: CodecTypes['pg/int4@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamp-temporal@1']['input'];
    };
    readonly Transaction: {
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly createdById: CodecTypes['pg/uuid@1']['input'];
      readonly fromLocationId: CodecTypes['pg/int4@1']['input'] | null;
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly notes: CodecTypes['pg/text@1']['input'] | null;
      readonly productId: CodecTypes['pg/uuid@1']['input'];
      readonly quantity: CodecTypes['pg/int4@1']['input'];
      readonly reference: CodecTypes['sql/varchar@1']['input'] | null;
      readonly status: 'DRAFT' | 'VALIDATED' | 'CANCELLED';
      readonly toLocationId: CodecTypes['pg/int4@1']['input'] | null;
      readonly type: 'RECEIPT' | 'DELIVERY' | 'TRANSFER' | 'ADJUSTMENT';
    };
    readonly User: {
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly email: CodecTypes['sql/varchar@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly name: CodecTypes['sql/varchar@1']['input'];
      readonly passwordHash: CodecTypes['sql/varchar@1']['input'];
      readonly role: 'ADMIN' | 'MANAGER' | 'STAFF';
    };
    readonly Warehouse: {
      readonly address: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly isActive: CodecTypes['pg/bool@1']['input'];
      readonly name: CodecTypes['sql/varchar@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly categories: {
      readonly description: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: Varchar<100>;
    };
    readonly locations: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: Varchar<100>;
      readonly type: 'STORAGE' | 'STAGING' | 'RETURNS';
      readonly warehouse_id: CodecTypes['pg/int4@1']['output'];
    };
    readonly products: {
      readonly category_id: CodecTypes['pg/int4@1']['output'];
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly name: Varchar<255>;
      readonly reorder_level: CodecTypes['pg/int4@1']['output'];
      readonly sku: Varchar<100>;
      readonly unit: Varchar<50>;
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['output'];
    };
    readonly stock_levels: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly location_id: CodecTypes['pg/int4@1']['output'];
      readonly product_id: CodecTypes['pg/uuid@1']['output'];
      readonly quantity: CodecTypes['pg/int4@1']['output'];
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['output'];
    };
    readonly transactions: {
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly created_by: CodecTypes['pg/uuid@1']['output'];
      readonly from_location_id: CodecTypes['pg/int4@1']['output'] | null;
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly notes: CodecTypes['pg/text@1']['output'] | null;
      readonly product_id: CodecTypes['pg/uuid@1']['output'];
      readonly quantity: CodecTypes['pg/int4@1']['output'];
      readonly reference: Varchar<100> | null;
      readonly status: 'DRAFT' | 'VALIDATED' | 'CANCELLED';
      readonly to_location_id: CodecTypes['pg/int4@1']['output'] | null;
      readonly type: 'RECEIPT' | 'DELIVERY' | 'TRANSFER' | 'ADJUSTMENT';
    };
    readonly users: {
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly email: Varchar<255>;
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly name: Varchar<255>;
      readonly password_hash: Varchar<255>;
      readonly role: 'ADMIN' | 'MANAGER' | 'STAFF';
    };
    readonly warehouses: {
      readonly address: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly is_active: CodecTypes['pg/bool@1']['output'];
      readonly name: Varchar<100>;
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly categories: {
      readonly description: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['sql/varchar@1']['input'];
    };
    readonly locations: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['sql/varchar@1']['input'];
      readonly type: 'STORAGE' | 'STAGING' | 'RETURNS';
      readonly warehouse_id: CodecTypes['pg/int4@1']['input'];
    };
    readonly products: {
      readonly category_id: CodecTypes['pg/int4@1']['input'];
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly name: CodecTypes['sql/varchar@1']['input'];
      readonly reorder_level: CodecTypes['pg/int4@1']['input'];
      readonly sku: CodecTypes['sql/varchar@1']['input'];
      readonly unit: CodecTypes['sql/varchar@1']['input'];
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['input'];
    };
    readonly stock_levels: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly location_id: CodecTypes['pg/int4@1']['input'];
      readonly product_id: CodecTypes['pg/uuid@1']['input'];
      readonly quantity: CodecTypes['pg/int4@1']['input'];
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['input'];
    };
    readonly transactions: {
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly created_by: CodecTypes['pg/uuid@1']['input'];
      readonly from_location_id: CodecTypes['pg/int4@1']['input'] | null;
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly notes: CodecTypes['pg/text@1']['input'] | null;
      readonly product_id: CodecTypes['pg/uuid@1']['input'];
      readonly quantity: CodecTypes['pg/int4@1']['input'];
      readonly reference: CodecTypes['sql/varchar@1']['input'] | null;
      readonly status: 'DRAFT' | 'VALIDATED' | 'CANCELLED';
      readonly to_location_id: CodecTypes['pg/int4@1']['input'] | null;
      readonly type: 'RECEIPT' | 'DELIVERY' | 'TRANSFER' | 'ADJUSTMENT';
    };
    readonly users: {
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly email: CodecTypes['sql/varchar@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly name: CodecTypes['sql/varchar@1']['input'];
      readonly password_hash: CodecTypes['sql/varchar@1']['input'];
      readonly role: 'ADMIN' | 'MANAGER' | 'STAFF';
    };
    readonly warehouses: {
      readonly address: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly is_active: CodecTypes['pg/bool@1']['input'];
      readonly name: CodecTypes['sql/varchar@1']['input'];
    };
  };
};

export namespace Models {
  export type public_Category = {
    description: CodecTypes['pg/text@1']['output'] | null;
    id: CodecTypes['pg/int4@1']['output'];
    name: Varchar<100>;
    products: public_Product[];
    readonly [RelationKeys]?: 'products';
  };
  export type public_Location = {
    id: CodecTypes['pg/int4@1']['output'];
    name: Varchar<100>;
    type: 'STORAGE' | 'STAGING' | 'RETURNS';
    warehouseId: CodecTypes['pg/int4@1']['output'];
    stockLevels: public_StockLevel[];
    transactionsFrom: public_Transaction[];
    transactionsTo: public_Transaction[];
    warehouse: public_Warehouse;
    readonly [RelationKeys]?: 'stockLevels' | 'transactionsFrom' | 'transactionsTo' | 'warehouse';
  };
  export type public_Product = {
    categoryId: CodecTypes['pg/int4@1']['output'];
    createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
    id: CodecTypes['pg/uuid@1']['output'];
    name: Varchar<255>;
    reorderLevel: CodecTypes['pg/int4@1']['output'];
    sku: Varchar<100>;
    unit: Varchar<50>;
    updatedAt: CodecTypes['pg/timestamp-temporal@1']['output'];
    category: public_Category;
    stockLevels: public_StockLevel[];
    transactions: public_Transaction[];
    readonly [RelationKeys]?: 'category' | 'stockLevels' | 'transactions';
  };
  export type public_StockLevel = {
    id: CodecTypes['pg/int4@1']['output'];
    locationId: CodecTypes['pg/int4@1']['output'];
    productId: CodecTypes['pg/uuid@1']['output'];
    quantity: CodecTypes['pg/int4@1']['output'];
    updatedAt: CodecTypes['pg/timestamp-temporal@1']['output'];
    location: public_Location;
    product: public_Product;
    readonly [RelationKeys]?: 'location' | 'product';
  };
  export type public_Transaction = {
    createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
    createdById: CodecTypes['pg/uuid@1']['output'];
    fromLocationId: CodecTypes['pg/int4@1']['output'] | null;
    id: CodecTypes['pg/uuid@1']['output'];
    notes: CodecTypes['pg/text@1']['output'] | null;
    productId: CodecTypes['pg/uuid@1']['output'];
    quantity: CodecTypes['pg/int4@1']['output'];
    reference: Varchar<100> | null;
    status: 'DRAFT' | 'VALIDATED' | 'CANCELLED';
    toLocationId: CodecTypes['pg/int4@1']['output'] | null;
    type: 'RECEIPT' | 'DELIVERY' | 'TRANSFER' | 'ADJUSTMENT';
    createdBy: public_User;
    fromLocation: public_Location | null;
    product: public_Product;
    toLocation: public_Location | null;
    readonly [RelationKeys]?: 'createdBy' | 'fromLocation' | 'product' | 'toLocation';
  };
  export type public_User = {
    createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
    email: Varchar<255>;
    id: CodecTypes['pg/uuid@1']['output'];
    name: Varchar<255>;
    passwordHash: Varchar<255>;
    role: 'ADMIN' | 'MANAGER' | 'STAFF';
    transactions: public_Transaction[];
    readonly [RelationKeys]?: 'transactions';
  };
  export type public_Warehouse = {
    address: CodecTypes['pg/text@1']['output'] | null;
    id: CodecTypes['pg/int4@1']['output'];
    isActive: CodecTypes['pg/bool@1']['output'];
    name: Varchar<100>;
    locations: public_Location[];
    readonly [RelationKeys]?: 'locations';
  };
}

export declare const models: {
  public: {
    Category: Models.public_Category;
    Location: Models.public_Location;
    Product: Models.public_Product;
    StockLevel: Models.public_StockLevel;
    Transaction: Models.public_Transaction;
    User: Models.public_User;
    Warehouse: Models.public_Warehouse;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly categories: {
              columns: {
                readonly description: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly name: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 100 };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'categories_name_key';
                  readonly columns: readonly ['name'];
                  readonly unique: true;
                },
              ];
              foreignKeys: readonly [];
            };
            readonly locations: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly name: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 100 };
                };
                readonly type: {
                  readonly nativeType: 'LocationType';
                  readonly codecId: 'pg/enum@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/enum@1', 'STORAGE'>;
                  };
                  readonly typeParams: { readonly typeName: 'LocationType' };
                };
                readonly warehouse_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'locations';
                    readonly columns: readonly ['warehouse_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'warehouses';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly products: {
              columns: {
                readonly category_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly created_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 255 };
                };
                readonly reorder_level: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
                readonly sku: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 100 };
                };
                readonly unit: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 50 };
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'products_sku_key';
                  readonly columns: readonly ['sku'];
                  readonly unique: true;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'products';
                    readonly columns: readonly ['category_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'categories';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly stock_levels: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly location_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly product_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly quantity: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'stock_levels_product_id_location_id_key';
                  readonly columns: readonly ['product_id', 'location_id'];
                  readonly unique: true;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'stock_levels';
                    readonly columns: readonly ['product_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'products';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'stock_levels';
                    readonly columns: readonly ['location_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'locations';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly transactions: {
              columns: {
                readonly created_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly created_by: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly from_location_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly notes: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly product_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly quantity: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly reference: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 100 };
                };
                readonly status: {
                  readonly nativeType: 'TransactionStatus';
                  readonly codecId: 'pg/enum@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/enum@1', 'DRAFT'>;
                  };
                  readonly typeParams: { readonly typeName: 'TransactionStatus' };
                };
                readonly to_location_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly type: {
                  readonly nativeType: 'TransactionType';
                  readonly codecId: 'pg/enum@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly typeName: 'TransactionType' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'transactions';
                    readonly columns: readonly ['product_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'products';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'transactions';
                    readonly columns: readonly ['from_location_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'locations';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'transactions';
                    readonly columns: readonly ['to_location_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'locations';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'transactions';
                    readonly columns: readonly ['created_by'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'users';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly users: {
              columns: {
                readonly created_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly email: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 255 };
                };
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 255 };
                };
                readonly password_hash: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 255 };
                };
                readonly role: {
                  readonly nativeType: 'Role';
                  readonly codecId: 'pg/enum@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/enum@1', 'STAFF'>;
                  };
                  readonly typeParams: { readonly typeName: 'Role' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'users_email_key';
                  readonly columns: readonly ['email'];
                  readonly unique: true;
                },
              ];
              foreignKeys: readonly [];
            };
            readonly warehouses: {
              columns: {
                readonly address: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly is_active: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
                readonly name: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 100 };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'warehouses_name_key';
                  readonly columns: readonly ['name'];
                  readonly unique: true;
                },
              ];
              foreignKeys: readonly [];
            };
          };
          readonly valueSet: {
            readonly LocationType: {
              readonly kind: 'valueSet';
              readonly values: readonly ['STORAGE', 'STAGING', 'RETURNS'];
            };
            readonly Role: {
              readonly kind: 'valueSet';
              readonly values: readonly ['ADMIN', 'MANAGER', 'STAFF'];
            };
            readonly TransactionStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly ['DRAFT', 'VALIDATED', 'CANCELLED'];
            };
            readonly TransactionType: {
              readonly kind: 'valueSet';
              readonly values: readonly ['RECEIPT', 'DELIVERY', 'TRANSFER', 'ADJUSTMENT'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly categories: { readonly namespace: 'public' & NamespaceId; readonly model: 'Category' };
    readonly locations: { readonly namespace: 'public' & NamespaceId; readonly model: 'Location' };
    readonly products: { readonly namespace: 'public' & NamespaceId; readonly model: 'Product' };
    readonly stock_levels: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'StockLevel';
    };
    readonly transactions: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Transaction';
    };
    readonly users: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
    readonly warehouses: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Warehouse';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Category: {
            readonly fields: {
              readonly description: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 100 };
                };
              };
            };
            readonly relations: {
              readonly products: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Product';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['categoryId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'categories';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly description: { readonly column: 'description' };
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
              };
            };
          };
          readonly Location: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 100 };
                };
              };
              readonly type: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/enum@1';
                  readonly typeParams: { readonly typeName: 'LocationType' };
                };
              };
              readonly warehouseId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly stockLevels: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'StockLevel';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['locationId'];
                };
              };
              readonly transactionsFrom: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Transaction';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['fromLocationId'];
                };
              };
              readonly transactionsTo: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Transaction';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['toLocationId'];
                };
              };
              readonly warehouse: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Warehouse';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['warehouseId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'locations';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly type: { readonly column: 'type' };
                readonly warehouseId: { readonly column: 'warehouse_id' };
              };
            };
          };
          readonly Product: {
            readonly fields: {
              readonly categoryId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 255 };
                };
              };
              readonly reorderLevel: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly sku: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 100 };
                };
              };
              readonly unit: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 50 };
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
            };
            readonly relations: {
              readonly category: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Category';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['categoryId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly stockLevels: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'StockLevel';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['productId'];
                };
              };
              readonly transactions: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Transaction';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['productId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'products';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly categoryId: { readonly column: 'category_id' };
                readonly createdAt: { readonly column: 'created_at' };
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly reorderLevel: { readonly column: 'reorder_level' };
                readonly sku: { readonly column: 'sku' };
                readonly unit: { readonly column: 'unit' };
                readonly updatedAt: { readonly column: 'updated_at' };
              };
            };
          };
          readonly StockLevel: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly locationId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly productId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly quantity: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
            };
            readonly relations: {
              readonly location: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Location';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['locationId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly product: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Product';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['productId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'stock_levels';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly locationId: { readonly column: 'location_id' };
                readonly productId: { readonly column: 'product_id' };
                readonly quantity: { readonly column: 'quantity' };
                readonly updatedAt: { readonly column: 'updated_at' };
              };
            };
          };
          readonly Transaction: {
            readonly fields: {
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly createdById: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly fromLocationId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly notes: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly productId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly quantity: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly reference: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 100 };
                };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/enum@1';
                  readonly typeParams: { readonly typeName: 'TransactionStatus' };
                };
              };
              readonly toLocationId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly type: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/enum@1';
                  readonly typeParams: { readonly typeName: 'TransactionType' };
                };
              };
            };
            readonly relations: {
              readonly createdBy: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['createdById'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly fromLocation: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Location';
                };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['fromLocationId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly product: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Product';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['productId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly toLocation: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Location';
                };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['toLocationId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'transactions';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly createdAt: { readonly column: 'created_at' };
                readonly createdById: { readonly column: 'created_by' };
                readonly fromLocationId: { readonly column: 'from_location_id' };
                readonly id: { readonly column: 'id' };
                readonly notes: { readonly column: 'notes' };
                readonly productId: { readonly column: 'product_id' };
                readonly quantity: { readonly column: 'quantity' };
                readonly reference: { readonly column: 'reference' };
                readonly status: { readonly column: 'status' };
                readonly toLocationId: { readonly column: 'to_location_id' };
                readonly type: { readonly column: 'type' };
              };
            };
          };
          readonly User: {
            readonly fields: {
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 255 };
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 255 };
                };
              };
              readonly passwordHash: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 255 };
                };
              };
              readonly role: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/enum@1';
                  readonly typeParams: { readonly typeName: 'Role' };
                };
              };
            };
            readonly relations: {
              readonly transactions: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Transaction';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['createdById'];
                };
              };
            };
            readonly storage: {
              readonly table: 'users';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly createdAt: { readonly column: 'created_at' };
                readonly email: { readonly column: 'email' };
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly passwordHash: { readonly column: 'password_hash' };
                readonly role: { readonly column: 'role' };
              };
            };
          };
          readonly Warehouse: {
            readonly fields: {
              readonly address: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly isActive: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 100 };
                };
              };
            };
            readonly relations: {
              readonly locations: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Location';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['warehouseId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'warehouses';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly address: { readonly column: 'address' };
                readonly id: { readonly column: 'id' };
                readonly isActive: { readonly column: 'is_active' };
                readonly name: { readonly column: 'name' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly insertOnConflictSkip: true;
      readonly insertOnConflictWithoutTarget: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'products';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'plainDateTimeNow'; readonly kind: 'generator' };
          readonly onUpdate: { readonly id: 'plainDateTimeNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'products';
            readonly field: 'updated_at';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'plainDateTimeNow'; readonly kind: 'generator' };
          readonly onUpdate: { readonly id: 'plainDateTimeNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'stock_levels';
            readonly field: 'updated_at';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'transactions';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'users';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
